language: ruby
sudo: false
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
before_install:
  - gem update bundler
branches:
  only:
    - master
jobs:
  include:
    - stage: test
      rvm: 2.5
      before_script: bundle install
      script: bundle exec rake rubocop
    - sript: bundle exec rake spec
