language: ruby
dist: trusty
cache: bundler
sudo: false
rvm:
  - 2.5
before_install:
  - gem update --system
  - gem update --remote bundler
  - gem --version
  - bundle --version
branches:
  only:
    - master
jobs:
  include:
    - stage: test
      script: bundle exec rake rubocop
    - stage: test
      script: bundle exec rake spec
